---

- name: install apt package
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items: "{{ supervisor_packages }}"

- name: install pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ supervisor_pip_packages }}"


- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/supervisor/conf.d
    - /var/log/supervisord

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/supervisor/{{ item }}"
  with_items:
    - supervisord.conf
    - conf.d/programs.conf
    - conf.d/events.conf
  notify:
    - restart supervisor

- name: service start
  service:
    name:  "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - supervisor
