---

- name: install apt package
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ supervisor_packages }}"

- name: install pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ supervisor_pip_packages }}"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ supervisor_user }}"
  with_items:
    - /etc/supervisor/conf.d
    - /var/log/supervisord
  tags: supervisor_config

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/supervisor/{{ item }}"
    owner: "{{ supervisor_user }}"
  with_items:
    - supervisord.conf
    - conf.d/programs.conf
    - conf.d/events.conf
  notify:
    - restart supervisor
  tags: supervisor_config

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - supervisor
